version: '3.8'

services:
  postgres.gcs_backup:
    build:
      dockerfile: Dockerfile
    environment:
      POSTGRES_DATABASE: "postgres"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

